FROM golang:1.23-alpine

RUN apk update && apk add --no-cache git bash curl netcat-openbsd

WORKDIR /app

COPY scripts/ ./scripts/

RUN chmod +x scripts/wait-for-it.sh

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["./scripts/wait-for-it.sh", "db", "5432", "--", "go", "test", "./..."]